<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-TJ6E03VU" failures="1" tests="11" name="com.mindtree.runner.TestRunner" time="160.601" errors="1" timestamp="2022-01-20T07:43:24 IST" skipped="0">
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="4.987"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="7.396"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="20.592"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="15.583"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="20.639"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="6.474"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="6.406"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="20.447">
    <failure message="expected [₹ 7493] but found [₹ 5124]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [₹ 7493] but found [₹ 5124]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.mindtree.pageobject.outstationpageobject.validate(outstationpageobject.java:83)
at com.mindtree.stepDefination.outstationstepdefinition.validate_car_type_under_booking_details(outstationstepdefinition.java:130)
at ✽.validate car type under booking details(file:///C:/Users/tejareddy/OneDrive/Desktop/Cucumberframework/Features/out.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="5.298"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="20.015"/>
  <testcase classname="com.mindtree.runner.TestRunner" name="runScenario" time="32.764">
    <error message="The step &#039;Select the first car&#039; and 1 other step(s) are undefined.
You can implement these steps using the snippet(s) below:

@Then(&quot;Select the first car&quot;)
public void select_the_first_car() {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
@Then(&quot;validate car in car details&quot;)
public void validate_car_in_car_details() {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
" type="io.cucumber.testng.UndefinedStepException">
      <![CDATA[io.cucumber.testng.UndefinedStepException: The step 'Select the first car' and 1 other step(s) are undefined.
You can implement these steps using the snippet(s) below:

@Then("Select the first car")
public void select_the_first_car() {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
@Then("validate car in car details")
public void validate_car_in_car_details() {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

at io.cucumber.core.runtime.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:69)
at io.cucumber.testng.TestCaseResultObserver.assertTestCasePassed(TestCaseResultObserver.java:23)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:133)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:110)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:110)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.mindtree.runner.TestRunner -->
